# Generated by Django 5.1 on 2024-08-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilities',
            name='image',
            field=models.ImageField(upload_to='reservation/facilities/'),
        ),
    ]
