# Generated by Django 5.1.1 on 2024-09-11 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservation_iduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilities',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
