# Generated by Django 5.1.1 on 2024-10-11 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0001_initial'),
        ('reservation', '0003_facilities_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='availability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.availability'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='facilities',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.facilities'),
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.DeleteModel(
            name='Facilities',
        ),
    ]
