# Generated by Django 5.0.7 on 2024-08-11 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='end',
            new_name='time_slot',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='available',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='start',
        ),
    ]
