# Generated by Django 5.0.7 on 2024-09-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lastname1',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Primer Apellido'),
        ),
    ]
