# Generated by Django 5.0.7 on 2024-09-02 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_lastname2_user_last_name2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_name2',
        ),
    ]
