# Generated by Django 5.0.7 on 2024-09-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_last_name2'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_name2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Segundo apellido'),
        ),
    ]
