# Generated by Django 5.0.7 on 2024-09-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_last_name2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False, verbose_name='is student'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Second last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Celphone'),
        ),
    ]
