# Generated by Django 5.1.1 on 2025-10-15 02:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facility', '0002_availability_is_restricted'),
        ('reservation', '0005_waitlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityRatingStats',
            fields=[
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rating_stats', serialize=False, to='facility.facilities')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Promedio de calificaciones (Composite)', max_digits=3)),
                ('total_ratings', models.IntegerField(default=0, help_text='Total de calificaciones recibidas')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estadísticas de Calificación',
                'verbose_name_plural': 'Estadísticas de Calificaciones',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(help_text='Calificación de 1 a 5 estrellas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='Comentario opcional del usuario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='facility.facilities')),
                ('reservation', models.OneToOneField(blank=True, help_text='Reserva asociada a esta calificación', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='reservation.reservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'reservation')},
            },
        ),
    ]
