# Generated by Django 5.1.1 on 2024-10-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='is_restricted',
            field=models.BooleanField(default=False),
        ),
    ]
